# Generated by Django 3.1.14 on 2022-05-30 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facebook', '0002_user_regis'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_regis',
            name='gender',
            field=models.CharField(default='male', max_length=255),
        ),
    ]
