# Generated by Django 3.1.14 on 2022-06-07 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facebook', '0007_auto_20220607_1645'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='price',
            field=models.IntegerField(default=100),
            preserve_default=False,
        ),
    ]
